# Generated by Django 5.2.7 on 2025-11-02 16:47

import uuid
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripDetailsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "distance",
                    models.FloatField(help_text="Total route distance in meters"),
                ),
                (
                    "duration",
                    models.FloatField(help_text="Total route duration in seconds"),
                ),
                (
                    "bbox",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Bounding box: [min_lon, min_lat, max_lon, max_lat]",
                        null=True,
                        size=4,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.FloatField(), size=2
                        ),
                        help_text="List of [lon, lat] coordinate pairs",
                        size=None,
                    ),
                ),
                ("steps", models.JSONField(help_text="List of navigation steps")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="trips.tripmodel",
                    ),
                ),
            ],
        ),
    ]
