# Generated by Django 5.2.7 on 2025-11-02 21:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_tripdetailsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripdetailsmodel",
            name="dropoff",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=[3, 2],
                help_text="Geocode for dropoff location",
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="tripdetailsmodel",
            name="origin",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=[3, 2],
                help_text="Geocode for origin location",
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="tripdetailsmodel",
            name="pickup",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=[3, 2],
                help_text="Geocode for pickup location",
                size=2,
            ),
        ),
    ]
